### ISSUE TITLE
Atualizar versão de plone.formwidget.namedfile

### ISSUE THREAD

**Issue by Dadlo** [plonegovbr/portalpadrao.release#1]
Conforme ticket https://github.com/plonegovbr/brasil.gov.portal/issues/162
Há erro na edição de alguns tiles (Banner e Basic News Article) que já foi solucionado na versão 1.0.10 de plone.formwidget.namedfile.
Dessa forma precisamos  atualizar plone.formwidget.namedfile para versão 1.0.10 (hoje está a 1.0.9).

Qual a forma indicada para essa alteração ser feita para próximos releases?

**Comment by taniaa** [comment]
Ralacionado com https://github.com/plonegovbr/brasil.gov.portal/issues/162
