### ISSUE TITLE
Versão do collective.googleanalytics

### ISSUE THREAD

**Issue by tcurvelo** [plonegovbr/portalpadrao.release#12]
Senhores,
Corrijam-se se eu estiver errado, mas eu acredito [que essa versão do collective.analytics](https://github.com/plonegovbr/portalpadrao.release/blob/master/1.1.4/versions.cfg#L515) (1.4.4) não funciona. Nela, o protocolo de autenticação é o OAuth1.0, que foi [descontinuado pelo Google](https://support.google.com/a/answer/162106?p=authsub&rd=3), enquanto as versões 1.5.x (sem releases ainda) usa OAuth2.0.

Como vocês estão usando o `collective.googleanalytics` hoje em dia?

**Comment by tcurvelo** [comment]
@hvelarde @rodfersou @idgserpro alguém?

**Comment by idgserpro** [comment]
@tcurvelo nós não usamos o collective.googleanalytics mas você parece estar certo. Você pode abrir um relato no repositório do collective.googleanalytics questionando sobre um novo release. Depois você avisa aqui que mudamos a pinagem.

**Comment by tcurvelo** [comment]
O release `1.5.0` do `collective.googleanalytics` foi feito!
https://pypi.python.org/pypi/collective.googleanalytics/1.5.0

**Comment by idgserpro** [comment]
@tcurvelo legal! Como não estamos utilizando o collective.googleanalytics no IDG, acho melhor remover a pinagem dele.
