### ISSUE TITLE
Release 1.1.5

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/portalpadrao.release#13]
Verificar se todos os relatos do milestone foram atendidos em

https://waffle.io/plonegovbr/brasil.gov.portal?milestone=1.1.5 (próximo release poderia usar o https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features#manage-your-ideas-with-projects ao invés do waffle, atende?)

Ações para o novo release:
- [x] As dependências plonegovbr (como brasil.gov.tiles, brasil.gov.portlets e etc) tem seus respectivos releases criados, tags geradas e pacotes disponibilizados no pypi;
  - [x] [brasil.gov.portal](https://github.com/plonegovbr/brasil.gov.portal/)
  - [x] [brasil.gov.tiles](https://github.com/plonegovbr/brasil.gov.tiles/)
  - [x] [brasil.gov.vcge 1.x](https://github.com/plonegovbr/brasil.gov.vcge/tree/1.0.x)
  - [x] ~[brasil.gov.vcge 2.x](https://github.com/plonegovbr/brasil.gov.vcge/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
  - [x] [brasil.gov.barra](https://github.com/plonegovbr/brasil.gov.barra/)
  - [x] [brasil.gov.portlets](https://github.com/plonegovbr/brasil.gov.portlets/)
  - [x] [brasil.gov.temas](https://github.com/plonegovbr/brasil.gov.temas/)
  - [x] ~[brasil.gov.agenda](https://github.com/plonegovbr/brasil.gov.agenda/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
  - [x] ~[brasil.gov.facetada](https://github.com/plonegovbr/brasil.gov.facetada/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
  - [x] ~[brasil.gov.paginadestaque](https://github.com/plonegovbr/brasil.gov.paginadestaque/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
- [x] Os releases de dependências plonegovbr feitas no passo anterior, as pinagens de dependências externas e do próprio Plone que foram testados durante o processo de geração de release são adicionadas/alteradas em https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg;
  - [x] [brasil.gov.portal](https://github.com/plonegovbr/brasil.gov.portal/)
  - [x] [brasil.gov.tiles](https://github.com/plonegovbr/brasil.gov.tiles/)
  - [x] [brasil.gov.vcge 1.x](https://github.com/plonegovbr/brasil.gov.vcge/tree/1.0.x)
  - [x] ~[brasil.gov.vcge 2.x](https://github.com/plonegovbr/brasil.gov.vcge/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
  - [x] [brasil.gov.barra](https://github.com/plonegovbr/brasil.gov.barra/)
  - [x] [brasil.gov.portlets](https://github.com/plonegovbr/brasil.gov.portlets/)
  - [x] [brasil.gov.temas](https://github.com/plonegovbr/brasil.gov.temas/)
  - [x] ~[brasil.gov.agenda](https://github.com/plonegovbr/brasil.gov.agenda/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
  - [x] ~[brasil.gov.facetada](https://github.com/plonegovbr/brasil.gov.facetada/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
  - [x] ~[brasil.gov.paginadestaque](https://github.com/plonegovbr/brasil.gov.paginadestaque/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
- [x] É feita uma revisão em todas as pinagens de https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg (procure por FIXME, HACK, BBB) para ver se poderá ser feita alguma modificação para aquele release em específico;
- [x] Restartar as builds do master das dependências plonegovbr no travis;
  - [x] [portal.buildout](https://travis-ci.org/plonegovbr/portal.buildout/)
  - [x] [brasil.gov.portal](https://travis-ci.org/plonegovbr/brasil.gov.portal/)
  - [x] [brasil.gov.tiles](https://travis-ci.org/plonegovbr/brasil.gov.tiles/)
  - [x] [brasil.gov.vcge 1.x](https://travis-ci.org/plonegovbr/brasil.gov.vcge/tree/1.0.x)
  - [x] ~[brasil.gov.vcge 2.x](https://travis-ci.org/plonegovbr/brasil.gov.vcge/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
  - [x] [brasil.gov.barra](https://travis-ci.org/plonegovbr/brasil.gov.barra/)
  - [x] [brasil.gov.portlets](https://travis-ci.org/plonegovbr/brasil.gov.portlets/)
  - [x] [brasil.gov.temas](https://travis-ci.org/plonegovbr/brasil.gov.temas/)
  - [x] ~[brasil.gov.agenda](https://travis-ci.org/plonegovbr/brasil.gov.agenda/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
  - [x] ~[brasil.gov.facetada](https://travis-ci.org/plonegovbr/brasil.gov.facetada/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
  - [x] ~[brasil.gov.paginadestaque](https://travis-ci.org/plonegovbr/brasil.gov.paginadestaque/)~ (Não teve nenhuma alteração no CHANGES.rst pra justificar um novo release)
- [x] Criar uma instância da última versão de brasil.gov.portal e efetuar um teste exploratório mínimo;
- [x] Quando todas as revisões tiverem sido feitas e estiver para lançar um release, o https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg será copiado para https://github.com/plonegovbr/portalpadrao.release, criando um novo diretório para aquele release;
- [x] É feita uma alteração no `extends` de https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/base.cfg informando esse novo release criado;
- [x] Restartar a build do master de portal.buildout no travis;
- [x] Aguardar o PR https://github.com/plonegovbr/portalpadrao.release/pull/15
- [x] Criação da tag do release em https://github.com/plonegovbr/portal.buildout;
- [x] Gerar o versions-sem-extends.cfg do release em https://github.com/plonegovbr/portalpadrao.release;
- [x] Criação da tag do release em https://github.com/plonegovbr/portalpadrao.release;
- [x] Envio de email pra lista plonegovbr pelo patrocinador indicando o lançamento desse novo release.

**Comment by idgserpro** [comment]
@hvelarde Poderia nos auxiliar com

> As dependências plonegovbr (como brasil.gov.tiles, brasil.gov.portlets e etc) tem seus respectivos releases criados, tags geradas e pacotes disponibilizados no pypi;

Para podermos dar prosseguimento às demais ações?

**Comment by hvelarde** [comment]
precisam release de quais pacotes? por favor listar claramente.

**Comment by idgserpro** [comment]
@hvelarde Os que estão listados na seção

> As dependências plonegovbr (como brasil.gov.tiles, brasil.gov.portlets e etc) tem seus respectivos releases criados, tags geradas e pacotes disponibilizados no pypi;

[na primeira mensagem desse issue](https://github.com/plonegovbr/portalpadrao.release/issues/13#issue-184084950). Terminando basta marcar no checkbox quais você finalizou o processo de geração de versão.

Poderia olhar o PR https://github.com/plonegovbr/brasil.gov.portal/pull/322 antes de criar um release de brasil.gov.portal? Seria interessante ter esse fix já nesse novo release.

**Comment by idgserpro** [comment]
@hvelarde os pacotes são brasil.gov.portal (favor ver o PR https://github.com/plonegovbr/brasil.gov.portal/pull/322 antes), brasil.gov.tiles, brasil.gov.vcge 1.x, brasil.gov.barra, brasil.gov.portlets e brasil.gov.temas, com os checkboxes na [1a mensagem pra marcar](https://github.com/plonegovbr/portalpadrao.release/issues/13#issue-184084950) quando terminar. Se tiver mais alguma dúvida só avisar.

**Comment by hvelarde** [comment]
pronto:

* https://pypi.python.org/pypi/brasil.gov.portal/1.1.5.1
* https://pypi.python.org/pypi/brasil.gov.tiles/1.2b1
* https://pypi.python.org/pypi/brasil.gov.vcge/1.1
* https://pypi.python.org/pypi/brasil.gov.barra/1.2
* https://pypi.python.org/pypi/brasil.gov.portlets/1.0rc2
* https://pypi.python.org/pypi/brasil.gov.temas/1.2

**Comment by idgserpro** [comment]
@hvelarde 

Os pacotes

https://pypi.python.org/pypi/brasil.gov.portal/1.1.5.1
https://pypi.python.org/pypi/brasil.gov.vcge/1.1
https://pypi.python.org/pypi/brasil.gov.portlets/1.0rc2
https://pypi.python.org/pypi/brasil.gov.temas/1.2

Estão com problemas de acento na descrição do pacote. Você está usando o zest.releaser? Será que é algum bug? Ou algum problema no seu editor?

**Comment by hvelarde** [comment]
estou usando sim, é um problema que já tinha visto e que não sempre acontece.

**Comment by idgserpro** [comment]
https://listas.interlegis.gov.br/pipermail/plonegov-br/2016-November/004184.html
