### ISSUE TITLE
Atualizar Products.CMFPlacefulWorkflow para 1.5.13

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/portalpadrao.release#4]
Atualizar a versão do Products.CMFPlacefulWorkflow para 1.5.13 para corrigir o erro "ValueError: 'Topic' is not a valid portal type."

**Comment by idgserpro** [comment]
Quando esse erro ocorre? Favor dar mais detalhes?

**Comment by claytonc** [comment]
Não instala.

Nome do produto no painel de controle "Suporte a cópia de trabalho (Iteração)"

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 580, in installProducts
    Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 512, in installProduct
    __traceback_info__: ('CMFPlacefulWorkflow',)
    Module Products.GenericSetup.tool, line 350, in runAllImportStepsFromProfile
    __traceback_info__: profile-Products.CMFPlacefulWorkflow:CMFPlacefulWorkflow
    Module Products.GenericSetup.tool, line 1100, in _runImportStepsFromContext
    Module Products.GenericSetup.tool, line 1015, in _doRunImportStep
    __traceback_info__: placeful_workflow
    Module Products.CMFPlacefulWorkflow.exportimport.workflow_policies, line 143, in importWorkflowPolicies
    Module Products.GenericSetup.utils, line 838, in importObjects
    __traceback_info__: portal_placeful_workflow
    Module Products.GenericSetup.utils, line 834, in importObjects
    __traceback_info__: portal_placeful_workflow/intranet
    Module Products.GenericSetup.utils, line 509, in _importBody
    Module Products.CMFCore.exportimport.workflow, line 61, in _importNode
    Module Products.CMFPlacefulWorkflow.exportimport.workflow_policies, line 127, in _initChains
    Module <string>, line 12, in setChain
    Module AccessControl.requestmethod, line 70, in _curried
    Module Products.CMFPlacefulWorkflow.DefaultWorkflowPolicy, line 279, in setChain

ValueError: 'Topic' is not a valid portal type.

**Comment by idgserpro** [comment]
Corrigido:

https://github.com/plonegovbr/portalpadrao.release/blob/2b5d7d11089ad4a6096b7cec248d46a80d9b2b9b/1.1.4/versions.cfg#L328
