### ISSUE TITLE
Remover entrada duplicada do setuptools no versions.cfg da release 1.1.3.1

### ISSUE THREAD

**Issue by brunobbbs** [plonegovbr/portalpadrao.release#5]
A entrada "setuptools = 0.6c11" aparece duas vezes no arquivo. O que pode prejudicar quando precisar alterar a versão.

**Comment by idgserpro** [comment]
O arquivo versions.cfg define versões que foram definidas em vários arquivos. Nesse caso, tanto:

http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg

quanto:

http://dist.plone.org/release/4.3.3/versions.cfg

definem "setuptools = 0.6c11". Veja [aqui](https://github.com/plonegovbr/portalpadrao.release/blob/master/1.1.3.1/versions.cfg#L224) e [aqui](http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg).

Se for necessário alterar a versão do setuptools, isso deve ser feito [daqui pra baixo](https://github.com/plonegovbr/portalpadrao.release/blob/master/1.1.3.1/versions.cfg#L453) no versions.cfg.

É bom manter os dois "setuptools = 0.6c11" para saber qual é a versão indicada originalmente pelos dois arquivos que os definem.
