### ISSUE TITLE
Não esquecer de, ao atualizar collective.cover para um próximo release, atualizar também o plone.app.blocks

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/portalpadrao.release#7]
Usar como base o https://github.com/collective/collective.cover/blob/master/versions-4.3.x.cfg

Essa atualização é necessária inclusive para que o erro de "quebrar a capa" não aconteça mais.

**Comment by idgserpro** [comment]
@hvelarde devemos atualizar o ```grokcore.view``` para 2.9 como indicado [aqui](https://github.com/collective/collective.cover/blob/master/versions-4.3.x.cfg#L21)?

**Comment by hvelarde** [comment]
isso já foi feito: https://github.com/plonegovbr/portalpadrao.release/commit/4525f74ea7168332097a74323b2c26eccd2b2bc9

se achar algum problema específico, por favor abrir uma issue bem clara.
