### ISSUE TITLE
Por que o versions.cfg foi criado da forma como é hoje?

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/portalpadrao.release#8]
Para atualizar o versions.cfg de um Plone ao outro nesse repositório, o trabalho é manual e custoso. Por que foi feito da forma como é hoje, e não simplesmente um `extends` para `http://dist.plone.org/release/4.3.X/versions.cfg` (no caso atual http://dist.plone.org/release/4.3.9/versions.cfg), e depois apenas as pinagens de pacotes brasil.gov.* e collective.*?

@ericof @hvelarde @rodfersou

**Comment by hvelarde** [comment]
eu acho que isso foi feito desse jeito para evitar problemas caso os outros servers não estivessem disponíveis; tem outras formas de solucionar por exemplo, simplesmente copiando esses outros arquivos completos e mantendo eles separados.

quem pode te orientar é o @ericof que foi quem tomou essa decisão.

**Comment by idgserpro** [comment]
De qualquer forma, para o 1.1.4 final presente na branch https://raw.githubusercontent.com/plonegovbr/portalpadrao.release/114_pending/1.1.4-pending/versions.cfg, manteremos o mesmo padrão: a única diferença é que agora as fontes dos arquivos copiados vão de forma *idêntica* ao nosso versions.cfg, incluindo os comentários, de forma a facilitar o diff em novos releases.

**Comment by idgserpro** [comment]
Para o release 1.1.5, iremos usar o extends das dependências do Plone tradicionais e iremos ter no versions.cfg apenas as pinagens dos pacotes do IDG e aquelas que sejam necessárias por questão de compatibilidade.

**Comment by hvelarde** [comment]
acho importante adicionar o [extends-cache](https://pypi.python.org/pypi/zc.buildout/2.5.0#basic-use-of-the-extends-cache) na configuração.

**Comment by idgserpro** [comment]
> acho importante adicionar o extends-cache na configuração.

Mas essa propriedade não espera um path *fixo*? Cada instalação pode ter um diretório diferente... Não seria o caso de só adicionar na documentação, para o usuário que precisa dessa funcionalidade, informar que ele pode adicionar em `~/.buildout/default.cfg` por exemplo? Ou adicionamos no extends um `versions-cache.cfg` e a pessoa adiciona nele o path (não sou muito fã dessa última opção porque adiciona *mais* um arquivo...)?

**Comment by hvelarde** [comment]
não tenho certeza, desconsiderem a sugestão.

**Comment by idgserpro** [comment]
Essa demanda está sendo atendida em https://github.com/plonegovbr/portal.buildout/blob/new_use_base_versions_cfg/buildout.d/versions.cfg. Quando o pull request https://github.com/plonegovbr/portal.buildout/pull/53 for atendido esse relato pode ser fechado.

**Comment by idgserpro** [comment]
Resolvido em https://github.com/plonegovbr/portal.buildout/issues/53
